# Gradle Settings
org.gradle.daemon=false
org.gradle.java.home=C\:\\Program Files\\Java\\jdk-21
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
minecraft_version=1.21.1
yarn_mappings=build.3
fabric_version=0.107.0

# Mod Properties
mod_version=3.1

# Dependencies
origins_version=1.13.0-alpha.9
modmenu_version=11.0.3