modLoader = "javafml"
loaderVersion = "[43,)"
license = "MIT"

[[mods]]
modId = "origins_randomiser"
version = "${version}"
displayName = "Origins Randomiser"
description = "Highly configurable mod that assigns you a random origin every time you die."

displayURL = "https://www.curseforge.com/minecraft/mc-mods/origins-randomiser"
issueTrackerURL = "https://github.com/QuantumXenon/origins-randomiser/issues"
authors = "TheQuantumXenon"
logoFile = "icon.png"

[[dependencies.origins_randomiser]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2]"

[[dependencies.origins_randomiser]]
modId = "origins"
mandatory = true
versionRange = "[1.19.2-1.5.0.6,)"