package quantumxenon.randomiser.enums;

public enum Message {
    COMMAND_DISABLED, RANDOMISER_DISABLED, RANDOMISER_ENABLED, LIMIT_COMMAND_USES, LIVES_DISABLED, LIVES_ENABLED, LIVES_REMAINING, LIVES_UNTIL_NEXT_RANDOMISE, OUT_OF_LIVES, OUT_OF_USES, RANDOM_ORIGIN_AFTER_LIVES, RANDOM_ORIGIN_AFTER_SLEEPS, SET_LIVES, SET_USES, SLEEPS_UNTIL_NEXT_RANDOMISE, UNLIMITED_USES, USES_LEFT
}